version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_codeing_test
    ports:
      - "9000:9000"
    depends_on:
      - mongo
      - redis
    environment:
      - JWT_SECRET=supersecret
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASS=secret123
      - REDIS_READ_HOST=redis
      - REDIS_READ_PORT=6379
      - REDIS_WRITE_HOST=redis
      - REDIS_WRITE_PORT=6379
      - REDIS_PUB_HOST=redis
      - REDIS_PUB_PORT=6379
    command: ./main

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 })' | mongosh mongodb://admin:secret123@mongo:27017/admin --quiet",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-codeing-test
    ports:
      - "7777:7777"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
