server:
  port: 9000
  allowOrigins:
    - "*"
  bodyLimit: "10M"
  timeout: 30s

jwt:
  secret: ${JWT_SECRET}
  ttl: 24h

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASS}
  dbname: codingTestDatabase

redis:
  nameSpace: golang_codeing_test
  read:
    host: ${REDIS_READ_HOST}
    port: ${REDIS_READ_PORT}
    password: ${REDIS_READ_PASSWORD}
    db: 0
  write:
    host: ${REDIS_WRITE_HOST}
    port: ${REDIS_WRITE_PORT}
    password: ${REDIS_WRITE_PASSWORD}
    db: 0
  pub:
    host: ${REDIS_PUB_HOST}
    port: ${REDIS_PUB_PORT}
    password: ${REDIS_PUB_PASSWORD}
    db: 0